export const queryKeyPrefixes = {
  viewer: "viewer",
  users: "users",
  resumes: "resumes",
  experiences: "experiences",
  education: "education",
  resumeProjects: "resume-projects",
  skillGroups: "skill-groups",
  certifications: "certifications",
  talks: "talks",
  volunteers: "volunteers",
  languages: "languages",
  contacts: "contacts",
  links: "links",
  summaries: "summaries",
  deviceSessions: "deviceSessions",
  ghAccessToken: "ghAccessToken",
  github: "github",
  pinnedProjects: "pinned-projects",
  savedProjects: "saved-projects",
  apiKeys: "api-keys",
  githubAccessToken: "github-access-token",
} as const;
