/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as DashboardSetiingsRouteImport } from './routes/_dashboard/setiings'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as PublicResumeIndexRouteImport } from './routes/_public/resume/index'
import { Route as DashboardResumesIndexRouteImport } from './routes/_dashboard/resumes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardResumesCreateIndexRouteImport } from './routes/_dashboard/resumes/create/index'
import { Route as DashboardResumesResumeIdIndexRouteImport } from './routes/_dashboard/resumes/$resumeId/index'
import { Route as VerificationFailedRouteImport } from './routes/verification/failed/index'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardSetiingsRoute = DashboardSetiingsRouteImport.update({
  id: '/setiings',
  path: '/setiings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const PublicResumeIndexRoute = PublicResumeIndexRouteImport.update({
  id: '/resume/',
  path: '/resume/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationFailedRoute = VerificationFailedRouteImport.update({
  id: '/verification/failed',
  path: '/verification/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumesCreateIndexRoute =
  DashboardResumesCreateIndexRouteImport.update({
    id: '/resumes/create/',
    path: '/resumes/create/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardResumesResumeIdIndexRoute =
  DashboardResumesResumeIdIndexRouteImport.update({
    id: '/resumes/$resumeId/',
    path: '/resumes/$resumeId/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/search': typeof SearchRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/profile': typeof DashboardProfileRoute
  '/setiings': typeof DashboardSetiingsRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/resumes/': typeof DashboardResumesIndexRoute
  '/resume/': typeof PublicResumeIndexRoute
  '/resumes/$resumeId/': typeof DashboardResumesResumeIdIndexRoute
  '/resumes/create/': typeof DashboardResumesCreateIndexRoute
  '/verification/failed': typeof VerificationFailedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/profile': typeof DashboardProfileRoute
  '/setiings': typeof DashboardSetiingsRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/resumes': typeof DashboardResumesIndexRoute
  '/resume': typeof PublicResumeIndexRoute
  '/resumes/$resumeId': typeof DashboardResumesResumeIdIndexRoute
  '/resumes/create': typeof DashboardResumesCreateIndexRoute
  '/verification/failed': typeof VerificationFailedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/search': typeof SearchRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/setiings': typeof DashboardSetiingsRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/resumes/': typeof DashboardResumesIndexRoute
  '/_public/resume/': typeof PublicResumeIndexRoute
  '/_dashboard/resumes/$resumeId/': typeof DashboardResumesResumeIdIndexRoute
  '/_dashboard/resumes/create/': typeof DashboardResumesCreateIndexRoute
  '/verification/failed': typeof VerificationFailedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/dashboard'
    | '/profile'
    | '/setiings'
    | '/auth/signup'
    | '/auth/'
    | '/api/auth/$'
    | '/resumes/'
    | '/resume/'
    | '/resumes/$resumeId/'
    | '/resumes/create/'
    | '/verification/failed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/dashboard'
    | '/profile'
    | '/setiings'
    | '/auth/signup'
    | '/auth'
    | '/api/auth/$'
    | '/resumes'
    | '/resume'
    | '/resumes/$resumeId'
    | '/resumes/create'
    | '/verification/failed'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_public'
    | '/auth'
    | '/search'
    | '/_dashboard/dashboard'
    | '/_dashboard/profile'
    | '/_dashboard/setiings'
    | '/auth/signup'
    | '/auth/'
    | '/api/auth/$'
    | '/_dashboard/resumes/'
    | '/_public/resume/'
    | '/_dashboard/resumes/$resumeId/'
    | '/_dashboard/resumes/create/'
    | '/verification/failed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  SearchRoute: typeof SearchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  VerificationFailedRoute: typeof VerificationFailedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/setiings': {
      id: '/_dashboard/setiings'
      path: '/setiings'
      fullPath: '/setiings'
      preLoaderRoute: typeof DashboardSetiingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_public/resume/': {
      id: '/_public/resume/'
      path: '/resume'
      fullPath: '/resume/'
      preLoaderRoute: typeof PublicResumeIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_dashboard/resumes/': {
      id: '/_dashboard/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof DashboardResumesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/resumes/create/': {
      id: '/_dashboard/resumes/create/'
      path: '/resumes/create'
      fullPath: '/resumes/create/'
      preLoaderRoute: typeof DashboardResumesCreateIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/resumes/$resumeId/': {
      id: '/_dashboard/resumes/$resumeId/'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId/'
      preLoaderRoute: typeof DashboardResumesResumeIdIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/verification/failed': {
      id: '/verification/failed'
      path: '/verification/failed'
      fullPath: '/verification/failed'
      preLoaderRoute: typeof VerificationFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSetiingsRoute: typeof DashboardSetiingsRoute
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute
  DashboardResumesResumeIdIndexRoute: typeof DashboardResumesResumeIdIndexRoute
  DashboardResumesCreateIndexRoute: typeof DashboardResumesCreateIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSetiingsRoute: DashboardSetiingsRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
  DashboardResumesResumeIdIndexRoute: DashboardResumesResumeIdIndexRoute,
  DashboardResumesCreateIndexRoute: DashboardResumesCreateIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicResumeIndexRoute: typeof PublicResumeIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicResumeIndexRoute: PublicResumeIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  SearchRoute: SearchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  VerificationFailedRoute: VerificationFailedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
