/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as SearchRouteImport } from "./routes/search.tsx";
import { Route as AuthLayoutRouteImport } from "./routes/auth/layout.tsx";
import { Route as DashboardLayoutRouteImport } from "./routes/_dashboard/layout.tsx";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthIndexRouteImport } from "./routes/auth/index";
import { Route as AuthSignupRouteImport } from "./routes/auth/signup.tsx";
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard/settings.tsx";
import { Route as DashboardReviewsRouteImport } from "./routes/_dashboard/reviews.tsx";
import { Route as DashboardProfileRouteImport } from "./routes/_dashboard/profile.tsx";
import { Route as DashboardOrdersRouteImport } from "./routes/_dashboard/orders.tsx";
import { Route as DashboardFavoritesRouteImport } from "./routes/_dashboard/favorites.tsx";
import { Route as DashboardDashboardRouteImport } from "./routes/_dashboard/dashboard.tsx";
import { Route as DashboardKitchensIndexRouteImport } from "./routes/_dashboard/kitchens/index";
import { Route as DashboardAdminIndexRouteImport } from "./routes/_dashboard/admin/index";
import { Route as DashboardKitchensNewIndexRouteImport } from "./routes/_dashboard/kitchens/new/index";
import { Route as DashboardKitchensKitchenIdIndexRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/index";
import { Route as DashboardKitchensKitchenIdStaffRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/staff.tsx";
import { Route as DashboardKitchensKitchenIdSettingsRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/settings.tsx";
import { Route as DashboardKitchensKitchenIdOrdersRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/orders.tsx";
import { Route as DashboardKitchensKitchenIdMenuRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/menu.tsx";
import { Route as DashboardKitchensKitchenIdCuisinesRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/cuisines.tsx";
import { Route as DashboardKitchensKitchenIdAuditRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/audit.tsx";
import { Route as DashboardKitchensKitchenIdUsersIndexRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/users/index";
import { Route as DashboardKitchensKitchenIdUsersNewRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/users/new.tsx";
import { Route as DashboardKitchensKitchenIdUsersUseridRouteImport } from "./routes/_dashboard/kitchens/$kitchenId/users/$userid.tsx";

const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthLayoutRoute,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => AuthLayoutRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: "/reviews",
  path: "/reviews",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: "/favorites",
  path: "/favorites",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensIndexRoute = DashboardKitchensIndexRouteImport.update({
  id: "/kitchens/",
  path: "/kitchens/",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensNewIndexRoute = DashboardKitchensNewIndexRouteImport.update({
  id: "/kitchens/new/",
  path: "/kitchens/new/",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensKitchenIdIndexRoute = DashboardKitchensKitchenIdIndexRouteImport.update({
  id: "/kitchens/$kitchenId/",
  path: "/kitchens/$kitchenId/",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensKitchenIdStaffRoute = DashboardKitchensKitchenIdStaffRouteImport.update({
  id: "/kitchens/$kitchenId/staff",
  path: "/kitchens/$kitchenId/staff",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensKitchenIdSettingsRoute =
  DashboardKitchensKitchenIdSettingsRouteImport.update({
    id: "/kitchens/$kitchenId/settings",
    path: "/kitchens/$kitchenId/settings",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardKitchensKitchenIdOrdersRoute = DashboardKitchensKitchenIdOrdersRouteImport.update({
  id: "/kitchens/$kitchenId/orders",
  path: "/kitchens/$kitchenId/orders",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensKitchenIdMenuRoute = DashboardKitchensKitchenIdMenuRouteImport.update({
  id: "/kitchens/$kitchenId/menu",
  path: "/kitchens/$kitchenId/menu",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensKitchenIdCuisinesRoute =
  DashboardKitchensKitchenIdCuisinesRouteImport.update({
    id: "/kitchens/$kitchenId/cuisines",
    path: "/kitchens/$kitchenId/cuisines",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardKitchensKitchenIdAuditRoute = DashboardKitchensKitchenIdAuditRouteImport.update({
  id: "/kitchens/$kitchenId/audit",
  path: "/kitchens/$kitchenId/audit",
  getParentRoute: () => DashboardLayoutRoute,
} as any);
const DashboardKitchensKitchenIdUsersIndexRoute =
  DashboardKitchensKitchenIdUsersIndexRouteImport.update({
    id: "/kitchens/$kitchenId/users/",
    path: "/kitchens/$kitchenId/users/",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardKitchensKitchenIdUsersNewRoute =
  DashboardKitchensKitchenIdUsersNewRouteImport.update({
    id: "/kitchens/$kitchenId/users/new",
    path: "/kitchens/$kitchenId/users/new",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);
const DashboardKitchensKitchenIdUsersUseridRoute =
  DashboardKitchensKitchenIdUsersUseridRouteImport.update({
    id: "/kitchens/$kitchenId/users/$userid",
    path: "/kitchens/$kitchenId/users/$userid",
    getParentRoute: () => DashboardLayoutRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/auth": typeof AuthLayoutRouteWithChildren;
  "/search": typeof SearchRoute;
  "/dashboard": typeof DashboardDashboardRoute;
  "/favorites": typeof DashboardFavoritesRoute;
  "/orders": typeof DashboardOrdersRoute;
  "/profile": typeof DashboardProfileRoute;
  "/reviews": typeof DashboardReviewsRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/auth/": typeof AuthIndexRoute;
  "/admin/": typeof DashboardAdminIndexRoute;
  "/kitchens/": typeof DashboardKitchensIndexRoute;
  "/kitchens/$kitchenId/audit": typeof DashboardKitchensKitchenIdAuditRoute;
  "/kitchens/$kitchenId/cuisines": typeof DashboardKitchensKitchenIdCuisinesRoute;
  "/kitchens/$kitchenId/menu": typeof DashboardKitchensKitchenIdMenuRoute;
  "/kitchens/$kitchenId/orders": typeof DashboardKitchensKitchenIdOrdersRoute;
  "/kitchens/$kitchenId/settings": typeof DashboardKitchensKitchenIdSettingsRoute;
  "/kitchens/$kitchenId/staff": typeof DashboardKitchensKitchenIdStaffRoute;
  "/kitchens/$kitchenId/": typeof DashboardKitchensKitchenIdIndexRoute;
  "/kitchens/new/": typeof DashboardKitchensNewIndexRoute;
  "/kitchens/$kitchenId/users/$userid": typeof DashboardKitchensKitchenIdUsersUseridRoute;
  "/kitchens/$kitchenId/users/new": typeof DashboardKitchensKitchenIdUsersNewRoute;
  "/kitchens/$kitchenId/users/": typeof DashboardKitchensKitchenIdUsersIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/search": typeof SearchRoute;
  "/dashboard": typeof DashboardDashboardRoute;
  "/favorites": typeof DashboardFavoritesRoute;
  "/orders": typeof DashboardOrdersRoute;
  "/profile": typeof DashboardProfileRoute;
  "/reviews": typeof DashboardReviewsRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/auth": typeof AuthIndexRoute;
  "/admin": typeof DashboardAdminIndexRoute;
  "/kitchens": typeof DashboardKitchensIndexRoute;
  "/kitchens/$kitchenId/audit": typeof DashboardKitchensKitchenIdAuditRoute;
  "/kitchens/$kitchenId/cuisines": typeof DashboardKitchensKitchenIdCuisinesRoute;
  "/kitchens/$kitchenId/menu": typeof DashboardKitchensKitchenIdMenuRoute;
  "/kitchens/$kitchenId/orders": typeof DashboardKitchensKitchenIdOrdersRoute;
  "/kitchens/$kitchenId/settings": typeof DashboardKitchensKitchenIdSettingsRoute;
  "/kitchens/$kitchenId/staff": typeof DashboardKitchensKitchenIdStaffRoute;
  "/kitchens/$kitchenId": typeof DashboardKitchensKitchenIdIndexRoute;
  "/kitchens/new": typeof DashboardKitchensNewIndexRoute;
  "/kitchens/$kitchenId/users/$userid": typeof DashboardKitchensKitchenIdUsersUseridRoute;
  "/kitchens/$kitchenId/users/new": typeof DashboardKitchensKitchenIdUsersNewRoute;
  "/kitchens/$kitchenId/users": typeof DashboardKitchensKitchenIdUsersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_dashboard": typeof DashboardLayoutRouteWithChildren;
  "/auth": typeof AuthLayoutRouteWithChildren;
  "/search": typeof SearchRoute;
  "/_dashboard/dashboard": typeof DashboardDashboardRoute;
  "/_dashboard/favorites": typeof DashboardFavoritesRoute;
  "/_dashboard/orders": typeof DashboardOrdersRoute;
  "/_dashboard/profile": typeof DashboardProfileRoute;
  "/_dashboard/reviews": typeof DashboardReviewsRoute;
  "/_dashboard/settings": typeof DashboardSettingsRoute;
  "/auth/signup": typeof AuthSignupRoute;
  "/auth/": typeof AuthIndexRoute;
  "/_dashboard/admin/": typeof DashboardAdminIndexRoute;
  "/_dashboard/kitchens/": typeof DashboardKitchensIndexRoute;
  "/_dashboard/kitchens/$kitchenId/audit": typeof DashboardKitchensKitchenIdAuditRoute;
  "/_dashboard/kitchens/$kitchenId/cuisines": typeof DashboardKitchensKitchenIdCuisinesRoute;
  "/_dashboard/kitchens/$kitchenId/menu": typeof DashboardKitchensKitchenIdMenuRoute;
  "/_dashboard/kitchens/$kitchenId/orders": typeof DashboardKitchensKitchenIdOrdersRoute;
  "/_dashboard/kitchens/$kitchenId/settings": typeof DashboardKitchensKitchenIdSettingsRoute;
  "/_dashboard/kitchens/$kitchenId/staff": typeof DashboardKitchensKitchenIdStaffRoute;
  "/_dashboard/kitchens/$kitchenId/": typeof DashboardKitchensKitchenIdIndexRoute;
  "/_dashboard/kitchens/new/": typeof DashboardKitchensNewIndexRoute;
  "/_dashboard/kitchens/$kitchenId/users/$userid": typeof DashboardKitchensKitchenIdUsersUseridRoute;
  "/_dashboard/kitchens/$kitchenId/users/new": typeof DashboardKitchensKitchenIdUsersNewRoute;
  "/_dashboard/kitchens/$kitchenId/users/": typeof DashboardKitchensKitchenIdUsersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/auth"
    | "/search"
    | "/dashboard"
    | "/favorites"
    | "/orders"
    | "/profile"
    | "/reviews"
    | "/settings"
    | "/auth/signup"
    | "/auth/"
    | "/admin/"
    | "/kitchens/"
    | "/kitchens/$kitchenId/audit"
    | "/kitchens/$kitchenId/cuisines"
    | "/kitchens/$kitchenId/menu"
    | "/kitchens/$kitchenId/orders"
    | "/kitchens/$kitchenId/settings"
    | "/kitchens/$kitchenId/staff"
    | "/kitchens/$kitchenId/"
    | "/kitchens/new/"
    | "/kitchens/$kitchenId/users/$userid"
    | "/kitchens/$kitchenId/users/new"
    | "/kitchens/$kitchenId/users/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/search"
    | "/dashboard"
    | "/favorites"
    | "/orders"
    | "/profile"
    | "/reviews"
    | "/settings"
    | "/auth/signup"
    | "/auth"
    | "/admin"
    | "/kitchens"
    | "/kitchens/$kitchenId/audit"
    | "/kitchens/$kitchenId/cuisines"
    | "/kitchens/$kitchenId/menu"
    | "/kitchens/$kitchenId/orders"
    | "/kitchens/$kitchenId/settings"
    | "/kitchens/$kitchenId/staff"
    | "/kitchens/$kitchenId"
    | "/kitchens/new"
    | "/kitchens/$kitchenId/users/$userid"
    | "/kitchens/$kitchenId/users/new"
    | "/kitchens/$kitchenId/users";
  id:
    | "__root__"
    | "/"
    | "/_dashboard"
    | "/auth"
    | "/search"
    | "/_dashboard/dashboard"
    | "/_dashboard/favorites"
    | "/_dashboard/orders"
    | "/_dashboard/profile"
    | "/_dashboard/reviews"
    | "/_dashboard/settings"
    | "/auth/signup"
    | "/auth/"
    | "/_dashboard/admin/"
    | "/_dashboard/kitchens/"
    | "/_dashboard/kitchens/$kitchenId/audit"
    | "/_dashboard/kitchens/$kitchenId/cuisines"
    | "/_dashboard/kitchens/$kitchenId/menu"
    | "/_dashboard/kitchens/$kitchenId/orders"
    | "/_dashboard/kitchens/$kitchenId/settings"
    | "/_dashboard/kitchens/$kitchenId/staff"
    | "/_dashboard/kitchens/$kitchenId/"
    | "/_dashboard/kitchens/new/"
    | "/_dashboard/kitchens/$kitchenId/users/$userid"
    | "/_dashboard/kitchens/$kitchenId/users/new"
    | "/_dashboard/kitchens/$kitchenId/users/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren;
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren;
  SearchRoute: typeof SearchRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth": {
      id: "/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard": {
      id: "/_dashboard";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof DashboardLayoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/": {
      id: "/auth/";
      path: "/";
      fullPath: "/auth/";
      preLoaderRoute: typeof AuthIndexRouteImport;
      parentRoute: typeof AuthLayoutRoute;
    };
    "/auth/signup": {
      id: "/auth/signup";
      path: "/signup";
      fullPath: "/auth/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof AuthLayoutRoute;
    };
    "/_dashboard/settings": {
      id: "/_dashboard/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/reviews": {
      id: "/_dashboard/reviews";
      path: "/reviews";
      fullPath: "/reviews";
      preLoaderRoute: typeof DashboardReviewsRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/profile": {
      id: "/_dashboard/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof DashboardProfileRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/orders": {
      id: "/_dashboard/orders";
      path: "/orders";
      fullPath: "/orders";
      preLoaderRoute: typeof DashboardOrdersRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/favorites": {
      id: "/_dashboard/favorites";
      path: "/favorites";
      fullPath: "/favorites";
      preLoaderRoute: typeof DashboardFavoritesRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/dashboard": {
      id: "/_dashboard/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardDashboardRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/": {
      id: "/_dashboard/kitchens/";
      path: "/kitchens";
      fullPath: "/kitchens/";
      preLoaderRoute: typeof DashboardKitchensIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/admin/": {
      id: "/_dashboard/admin/";
      path: "/admin";
      fullPath: "/admin/";
      preLoaderRoute: typeof DashboardAdminIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/new/": {
      id: "/_dashboard/kitchens/new/";
      path: "/kitchens/new";
      fullPath: "/kitchens/new/";
      preLoaderRoute: typeof DashboardKitchensNewIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/": {
      id: "/_dashboard/kitchens/$kitchenId/";
      path: "/kitchens/$kitchenId";
      fullPath: "/kitchens/$kitchenId/";
      preLoaderRoute: typeof DashboardKitchensKitchenIdIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/staff": {
      id: "/_dashboard/kitchens/$kitchenId/staff";
      path: "/kitchens/$kitchenId/staff";
      fullPath: "/kitchens/$kitchenId/staff";
      preLoaderRoute: typeof DashboardKitchensKitchenIdStaffRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/settings": {
      id: "/_dashboard/kitchens/$kitchenId/settings";
      path: "/kitchens/$kitchenId/settings";
      fullPath: "/kitchens/$kitchenId/settings";
      preLoaderRoute: typeof DashboardKitchensKitchenIdSettingsRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/orders": {
      id: "/_dashboard/kitchens/$kitchenId/orders";
      path: "/kitchens/$kitchenId/orders";
      fullPath: "/kitchens/$kitchenId/orders";
      preLoaderRoute: typeof DashboardKitchensKitchenIdOrdersRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/menu": {
      id: "/_dashboard/kitchens/$kitchenId/menu";
      path: "/kitchens/$kitchenId/menu";
      fullPath: "/kitchens/$kitchenId/menu";
      preLoaderRoute: typeof DashboardKitchensKitchenIdMenuRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/cuisines": {
      id: "/_dashboard/kitchens/$kitchenId/cuisines";
      path: "/kitchens/$kitchenId/cuisines";
      fullPath: "/kitchens/$kitchenId/cuisines";
      preLoaderRoute: typeof DashboardKitchensKitchenIdCuisinesRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/audit": {
      id: "/_dashboard/kitchens/$kitchenId/audit";
      path: "/kitchens/$kitchenId/audit";
      fullPath: "/kitchens/$kitchenId/audit";
      preLoaderRoute: typeof DashboardKitchensKitchenIdAuditRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/users/": {
      id: "/_dashboard/kitchens/$kitchenId/users/";
      path: "/kitchens/$kitchenId/users";
      fullPath: "/kitchens/$kitchenId/users/";
      preLoaderRoute: typeof DashboardKitchensKitchenIdUsersIndexRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/users/new": {
      id: "/_dashboard/kitchens/$kitchenId/users/new";
      path: "/kitchens/$kitchenId/users/new";
      fullPath: "/kitchens/$kitchenId/users/new";
      preLoaderRoute: typeof DashboardKitchensKitchenIdUsersNewRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
    "/_dashboard/kitchens/$kitchenId/users/$userid": {
      id: "/_dashboard/kitchens/$kitchenId/users/$userid";
      path: "/kitchens/$kitchenId/users/$userid";
      fullPath: "/kitchens/$kitchenId/users/$userid";
      preLoaderRoute: typeof DashboardKitchensKitchenIdUsersUseridRouteImport;
      parentRoute: typeof DashboardLayoutRoute;
    };
  }
}

interface DashboardLayoutRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute;
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute;
  DashboardOrdersRoute: typeof DashboardOrdersRoute;
  DashboardProfileRoute: typeof DashboardProfileRoute;
  DashboardReviewsRoute: typeof DashboardReviewsRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute;
  DashboardKitchensIndexRoute: typeof DashboardKitchensIndexRoute;
  DashboardKitchensKitchenIdAuditRoute: typeof DashboardKitchensKitchenIdAuditRoute;
  DashboardKitchensKitchenIdCuisinesRoute: typeof DashboardKitchensKitchenIdCuisinesRoute;
  DashboardKitchensKitchenIdMenuRoute: typeof DashboardKitchensKitchenIdMenuRoute;
  DashboardKitchensKitchenIdOrdersRoute: typeof DashboardKitchensKitchenIdOrdersRoute;
  DashboardKitchensKitchenIdSettingsRoute: typeof DashboardKitchensKitchenIdSettingsRoute;
  DashboardKitchensKitchenIdStaffRoute: typeof DashboardKitchensKitchenIdStaffRoute;
  DashboardKitchensKitchenIdIndexRoute: typeof DashboardKitchensKitchenIdIndexRoute;
  DashboardKitchensNewIndexRoute: typeof DashboardKitchensNewIndexRoute;
  DashboardKitchensKitchenIdUsersUseridRoute: typeof DashboardKitchensKitchenIdUsersUseridRoute;
  DashboardKitchensKitchenIdUsersNewRoute: typeof DashboardKitchensKitchenIdUsersNewRoute;
  DashboardKitchensKitchenIdUsersIndexRoute: typeof DashboardKitchensKitchenIdUsersIndexRoute;
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardKitchensIndexRoute: DashboardKitchensIndexRoute,
  DashboardKitchensKitchenIdAuditRoute: DashboardKitchensKitchenIdAuditRoute,
  DashboardKitchensKitchenIdCuisinesRoute: DashboardKitchensKitchenIdCuisinesRoute,
  DashboardKitchensKitchenIdMenuRoute: DashboardKitchensKitchenIdMenuRoute,
  DashboardKitchensKitchenIdOrdersRoute: DashboardKitchensKitchenIdOrdersRoute,
  DashboardKitchensKitchenIdSettingsRoute: DashboardKitchensKitchenIdSettingsRoute,
  DashboardKitchensKitchenIdStaffRoute: DashboardKitchensKitchenIdStaffRoute,
  DashboardKitchensKitchenIdIndexRoute: DashboardKitchensKitchenIdIndexRoute,
  DashboardKitchensNewIndexRoute: DashboardKitchensNewIndexRoute,
  DashboardKitchensKitchenIdUsersUseridRoute: DashboardKitchensKitchenIdUsersUseridRoute,
  DashboardKitchensKitchenIdUsersNewRoute: DashboardKitchensKitchenIdUsersNewRoute,
  DashboardKitchensKitchenIdUsersIndexRoute: DashboardKitchensKitchenIdUsersIndexRoute,
};

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
);

interface AuthLayoutRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
};

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(AuthLayoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  SearchRoute: SearchRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
